
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'collageify'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${DB_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${DB_PW}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${DB_PW} 
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose: # Opens port 3306 on the container 
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  backen
# Names our volume
volumes:
  my-db: